# Generated by Django 5.2.3 on 2025-07-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="maessage",
            new_name="message",
        ),
    ]
